export type Theme="neutral"|"gold"|"cyan"; export type Plan="demo"|"expansion"|"diamond";
export type GenRequest={prompt:string;lang?:"es"|"en"|"fr";theme?:Theme;plan?:Plan};
export type GenResponse={seed:number;theme:Theme;plan:Plan;lang:"es"|"en"|"fr";layout:Array<{t:"hero";title:string;subtitle:string;cta:string}|{t:"features";items:{title:string;desc:string}[]}|{t:"gallery";images:string[]}|{t:"cta";title:string;button:string}|{t:"footer"}>};
function hash(s:string){let h=0;for(let i=0;i<s.length;i++){h=(h<<5)-h+s.charCodeAt(i);h|=0;}return Math.abs(h);}
function pick<T>(a:T[],i:number){return a[i%a.length];}
export function generate(req:GenRequest):GenResponse{
  const lang=req.lang??"es"; const plan=(req.plan??"demo") as Plan; const theme:Theme=req.theme??pick<Theme>(["neutral","gold","cyan"],hash(req.prompt)); const seed=hash(req.prompt+"|"+lang);
  const dict={es:{cta:"Hablar con Pulse",feat:["Rápido","Elegante","Listo para vender"],desc:["Tu web en minutos con bloques premium.","Diseño AA, limpio y con foco.","SEO básico e i18n listos."],final:"¿Listo para tu web?",btn:"Crear con Pulse"},
              en:{cta:"Talk to Pulse",feat:["Fast","Elegant","Ready to sell"],desc:["Your site in minutes with premium blocks.","AA design, clean and focused.","Basic SEO and i18n ready."],final:"Ready for your site?",btn:"Build with Pulse"},
              fr:{cta:"Parler à Pulse",feat:["Rapide","Élégant","Prêt à vendre"],desc:["Votre site en minutes avec des blocs premium.","Design AA, propre et ciblé.","SEO de base et i18n prêts."],final:"Prêt pour votre site ?",btn:"Créer avec Pulse"}}[lang];
  const title=req.prompt.length>8?req.prompt:"Website para tu idea";
  const subtitle=lang==="es"?"Generada por Pulse con bloques curados.":lang==="en"?"Generated by Pulse with curated blocks.":"Généré par Pulse avec des blocs soignés.";
  const layout:[GenResponse["layout"][number], ...GenResponse["layout"]] = [
    {t:"hero",title,subtitle,cta:dict.cta},
    {t:"features",items:[{title:dict.feat[0],desc:dict.desc[0]},{title:dict.feat[1],desc:dict.desc[1]},{title:dict.feat[2],desc:dict.desc[2]}]},
    {t:"gallery",images:Array.from({length:8}).map((_,i)=>`/uihut/placeholder-${i+1}.png`)},
    {t:"cta",title:dict.final,button:dict.btn},
    {t:"footer"}
  ];
  return {seed,theme,plan,lang,layout};
}
